version: "3.7"

services:
  postgres:
    image: postgres:alpine
    env_file:
      - ./env_defaults
    ports:
      - 41756:5432
    networks:
      - airflow_tests_net

  airflow_scheduler:
    image: jjjax/airflow-docker-light-test
    env_file:
      - ./env_defaults
    environment:
      UPGRADE_DB: "true"
      SLEEP: 2
    depends_on:
      - postgres
    volumes:
      - ./tests:/tests
      - ./dags:/opt/airflow/dags
    networks:
      - airflow_tests_net
    command: airflow scheduler

  airflow_tests:
    image: jjjax/airflow-docker-light-test
    build:
      args:
        PYTHON_DEPS: requirements.test.txt
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env_defaults
    environment:
      SLEEP: 3
    depends_on:
      - airflow_scheduler
    volumes:
      - ./tests:/tests
      - ./dags:/opt/airflow/dags
      - ./some:/opt/airflow
    networks:
      - airflow_tests_net
    command: pytest -c /tests/pytest.ini -s -v /tests/test_all.py::test_dag_complex

networks:
  airflow_tests_net:
    name: airflow_tests_net
