# The file can be used for auto-testing and local development.
version: "3.7"

services:
  postgres:
    image: postgres:alpine
    env_file:
      - src/env_defaults
    ports:
      - 41756:5432
    networks:
      - airflow_tests_net

  airflow_scheduler:
    image: jjjax/airflow-docker-light-test
    build:
      args:
        PYTHON_DEPS: requirements.test.txt
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - airflow:/opt/airflow
      - ./tests:/tests
      - ./dags:/opt/airflow/dags
    networks:
      - airflow_tests_net
    environment:
      UPGRADE_DB: "true"
      SLEEP: 2
    env_file:
      - src/env_defaults
    command: airflow scheduler

  airflow_tests:
    image: jjjax/airflow-docker-light-test
    depends_on:
      - airflow_scheduler
    volumes:
      - airflow:/opt/airflow
      - ./tests:/tests
      - ./dags:/opt/airflow/dags
    networks:
      - airflow_tests_net
    environment:
      SLEEP: 6
    env_file:
      - src/env_defaults
    command: pytest -c /tests/pytest.ini -s -v

volumes:
  airflow:

networks:
  airflow_tests_net:
    name: airflow_tests_net
