# The file can be used as a sample for running Airflow.
version: "3.7"

services:
  postgres:
    image: postgres:alpine
    env_file:
      - src/env_defaults
    ports:
      - 41756:5432
    networks:
      - airflow_light_net

  airflow_scheduler:
    image: jjjax/airflow-docker-light:1.10.9
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - airflow:/opt/airflow
    networks:
      - airflow_light_net
    environment:
      UPGRADE_DB: "true"
    env_file:
      - src/env_defaults
    restart: on-failure
    command: airflow scheduler

  airflow_webserver:
    image: jjjax/airflow-docker-light:1.10.9
    depends_on:
      - airflow_scheduler
    volumes:
      - airflow:/opt/airflow
    networks:
      - airflow_light_net
    ports:
      - 8080:8080
    env_file:
      - src/env_defaults
    restart: on-failure
    command: airflow webserver

volumes:
  airflow:

networks:
  airflow_light_net:
    name: airflow_light_net
